export enum UserRole {
  ADMIN = 'ADMIN',
  COORDINATOR = 'COORDINATOR',
  LECTURER = 'LECTURER',
  CLASS_REP = 'CLASS_REP',
  SUPERVISOR = 'SUPERVISOR',
  ONLINE_SUPERVISOR = 'ONLINE_SUPERVISOR'
}

export enum SessionType {
  LECTURE = 'LECTURE',
  SEMINAR = 'SEMINAR',
  LAB = 'LAB',
  VIRTUAL = 'VIRTUAL',
  HYBRID = 'HYBRID'
}
